name: test_project
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using flutter pub publish. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
version: 1.0.0+1

environment:
  sdk: ^3.7.0

# Dependencies specify other packages that your package needs in order to work.
dependencies:
  flutter:
    sdk: flutter

  provider: ^6.0.5
  # The following adds the Cupertino Icons font to your application.
  cupertino_icons: ^1.0.8

  # Pakiet http do komunikacji z API
  http: ^0.13.0

  # Pakiet shared_preferences do przechowywania danych lokalnych (np. tokenu)
  shared_preferences: ^2.0.15
  flutter_launcher_icons: ^0.14.3
  google_fonts: ^4.0.4
  simple_gradient_text: ^1.3.0
  google_maps_flutter: ^2.2.1
  geocoding: ^3.0.0
  geolocator: ^13.0.2
  flutter_dotenv: ^5.0.2
  google_maps_webservice: ^0.0.20-nullsafety.5
  jwt_decoder: ^2.0.1
  flutter_secure_storage: ^9.2.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  # Pakiet do linterów i dobrych praktyk kodowania
  flutter_lints: ^5.0.0

flutter_launcher_icons: ^0.9.2

flutter_icons:
  android: true
  ios: true
  image_path: "assets/icon.jpg"


flutter:

  uses-material-design: true

  assets:
  - .env
  - assets/frocar_logo.png
  - assets/car.png
  - assets/map_styles/light_mode.json
  - assets/map_styles/dark_mode.json